#include "std_msgs/msg/Header.idl"
#include "autoware_auto_msgs/msg/Waypoint.idl"

module autoware_auto_msgs {
    module msg {
        struct Lane {
            std_msgs::msg::Header header;

            @verbatim (language="comment", text=
            " increment")
            int32 increment;
            int32 lane_id;
            sequence<autoware_auto_msgs::msg::Waypoint> clusters;

            uint32 lane_index;
            float cost;
            float closest_object_distance;
            float closest_object_velocity;

            boolean is_blocked;
        };
    };
};

