#include "std_msgs/msg/Header.idl"

module autoware_auto_msgs {
  module msg {
    @verbatim (language="comment", text=
      " Struct of projected matrix from vector map on camera plane ")
    struct ProjectionMatrix {
        std_msgs::msg::Header header;

        @verbatim (language="comment", text=
        " matrix containing projection configuration")
        sequence<float, 16> projection_matrix;
    };
  };
};