#include "autoware_auto_msgs/msg/TrafficLight.idl"

module autoware_auto_msgs {
  module msg {
    @verbatim (language="comment", text=
    " A TrafficSignal is defined here as a group of multiple TrafficLights" "\n"
    " which each represent a single light, indicator, or bulb.")
    struct TrafficSignal {
      @verbatim (language="comment", text=
      " A value of 0 indicates an invalid map_primitive_id such as the" "\n"
      " case where the signal has not been associated with a map primitive.")
      @default (value=0)
      int32 map_primitive_id;

      sequence<autoware_auto_msgs::msg::TrafficLight, 10> lights;
    };
  };
};