#include "geometry_msgs/msg/PoseStamped.idl"
#include "geometry_msgs/msg/TwistStamped.idl"
#include "autoware_auto_msgs/msg/DTLane.idl"
#include "autoware_auto_msgs/msg/WaypointState.idl"

module autoware_auto_msgs {
    module msg {
        module Direction_Constants {
            const uint32 FORWARD = 0;
            const uint32 FORWARD_LEFT = 1;
            const uint32 FORWARD_RIGHT = 2;
            const uint32 BACKWARD = 3;
            const uint32 BACKWARD_LEFT = 4;
            const uint32 BACKWARD_RIGHT = 5;
            const uint32 STANDSTILL = 6;
        };

        struct Waypoint {
            @verbatim (language="comment", text=
            " global id")
            int32 gid;

            @verbatim (language="comment", text=
            " local id")
            int32 lid;

            geometry_msgs::msg::PoseStamped pose;
            geometry_msgs::msg::TwistStamped twist;
            autoware_auto_msgs::msg::DTLane dtlane;

            int32 change_flag;

            autoware_auto_msgs::msg::WaypointState wpstate;

            uint32 lane_id;
            uint32 left_lane_id;
            uint32 right_lane_id;
            uint32 stop_line_id;

            float cost;
            float time_cost;

            @verbatim (language="comment", text=
            " Lane Direction")
            uint32 direction;
        };
    };
};


