module autoware_auto_msgs {
    module msg {
        module WaypointState_Constants {
            const uint8 NULLSTATE=0;
            const uint8 STR_LEFT=1;
            const uint8 STR_RIGHT=2;
            const uint8 STR_STRAIGHT=3;
            const uint8 STR_BACK=4;
            const uint8 TYPE_STOPLINE=1;
            const uint8 TYPE_STOP=2;
            const uint8 TYPE_EVENT_NULL = 0;
            const uint8 TYPE_EVENT_GOAL = 1;
            const uint8 TYPE_EVENT_MIDDLE_GOAL = 2;
            const uint8 TYPE_EVENT_POSITION_STOP = 3;
            const uint8 TYPE_EVENT_BUS_STOP = 4;
            const uint8 TYPE_EVENT_PARKING = 5;
        };

        struct WaypointState {
            int32 aid;

            @verbatim (language="comment", text=
            " lane change")
            uint8 lanechange_state;

            @verbatim (language="comment", text=
            " bilinker")
            uint8 steering_state;

            uint8 accel_state;

            @verbatim (language="comment", text=
            " 1 is stopline, 2 is stop which can only be released manually.")
            uint8 stop_state;
            
            uint8 event_state;
        };
    };
};